### ISSUE TITLE
why database.getAllNights() not used in Coroutines and there is no exception 

### ISSUE THREAD

**Issue by mrrrxiii** [udacity/andfun-kotlin-sleep-tracker#13]
https://github.com/udacity/andfun-kotlin-sleep-tracker/blob/b48d6083c6374d45e681b2b740a3686163beb8b5/app/src/main/java/com/example/android/trackmysleepquality/sleeptracker/SleepTrackerViewModel.kt#L55

**Comment by doilio** [comment]
Hi @mrrrxiii
Because Room generates all the necessary code to update the LiveData object when a database is updated. The generated code runs the query asynchronously on a background thread when needed. This pattern is useful for keeping the data displayed in a UI in sync with the data stored in a database.

**Comment by marcoongithubnow** [comment]
Thanks

**Comment by HasanElHefnawy** [comment]
Note that `nights` is needed to be `LiveData` to be mapped to other `LiveData`, i.e., `nightsString` and `clearButtonVisible`. Also, note that `LiveData` and `suspend` can't be used together. If you try to do that, you'll get an error similar to `error: Not sure how to convert a Cursor to this method's return type`.

**Comment by SudKul** [comment]
To All, we recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors.
